#pragma once
#ifndef GLOBALS_INPUT_MANAGER_H
#define GLOBALS_INPUT_MANAGER_H

#include "input.h"

enum input_keys {
    eKEY_W = GLFW_KEY_W,
    eKEY_S = GLFW_KEY_S,
    eKEY_A = GLFW_KEY_A,
    eKEY_D = GLFW_KEY_D,
    eKEY_SPACE = GLFW_KEY_SPACE,
    eKEY_ENTER = GLFW_KEY_ENTER,
    eKEY_ESCAPE = GLFW_KEY_ESCAPE,
    eKEY_LEFT = GLFW_KEY_LEFT,
    eKEY_RIGHT = GLFW_KEY_RIGHT,
    eKEY_UP = GLFW_KEY_UP,
    eKEY_DOWN = GLFW_KEY_DOWN,
    eKEY_TAB = GLFW_KEY_TAB,
    eKEY_BACKSPACE = GLFW_KEY_BACKSPACE,
    eKEY_DELETE = GLFW_KEY_DELETE,
    eKEY_LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
    eKEY_RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT,
    eKEY_LEFT_CTRL = GLFW_KEY_LEFT_CONTROL,
    eKEY_RIGHT_CTRL = GLFW_KEY_RIGHT_CONTROL,
    eKEY_LEFT_ALT = GLFW_KEY_LEFT_ALT,
    eKEY_RIGHT_ALT = GLFW_KEY_RIGHT_ALT,
    eKEY_F1 = GLFW_KEY_F1,
    eKEY_F2 = GLFW_KEY_F2,
    eKEY_F3 = GLFW_KEY_F3,
    eKEY_F4 = GLFW_KEY_F4,
    eKEY_F5 = GLFW_KEY_F5,
    eKEY_F6 = GLFW_KEY_F6,
    eKEY_F7 = GLFW_KEY_F7,
    eKEY_F8 = GLFW_KEY_F8,
    eKEY_F9 = GLFW_KEY_F9,
    eKEY_F10 = GLFW_KEY_F10,
    eKEY_F11 = GLFW_KEY_F11,
    eKEY_F12 = GLFW_KEY_F12,
    eKEY_0 = GLFW_KEY_0,
    eKEY_1 = GLFW_KEY_1,
    eKEY_2 = GLFW_KEY_2,
    eKEY_3 = GLFW_KEY_3,
    eKEY_4 = GLFW_KEY_4,
    eKEY_5 = GLFW_KEY_5,
    eKEY_6 = GLFW_KEY_6,
    eKEY_7 = GLFW_KEY_7,
    eKEY_8 = GLFW_KEY_8,
    eKEY_9 = GLFW_KEY_9
};

extern input_manager* global_input_manager;


#endif // GLOBALS_H