#pragma once
#define ENGINE_SHADER_DEFUALT 0
#define ENGINE_SHADER_BILLBOARD 1
#define ENGINE_SHADER_PREPASS 2
#define ENGINE_SHADER_CLUSTER_COMP 3
#define ENGINE_SHADER_CLUSTER_CULL 4
#define ENGINE_SHADER_MOUSEPICK 5